config:
  heading-style: # MD003
    style: consistent # Maybe settle with atx or setex
  ul-style: # MD004
    style: dash
  no-trailing-spaces: # MD009
    strict: true # Include unnecessary breaks
  no-hard-tabs: # MD010
    code_blocks: false # Ignore code blocks
    spaces_per_tab: 4 # When fixing, replace a tab with 4 spaces
  line-length: # MD013
    code_blocks: false
    heading_line_length: 100
  no-missing-space-atx: false # MD018 this breaks tags on obsidian
  code-fence-style: # MD048
    style: backtick
  emphasis-style: # MD049
    style: consistent # Sometimes _, sometimes *
  strong-style: # MD050
    style: asterisk # Use **
  table-pipe-style: # MD055
    style: leading_and_trailing

noBanner: true
noProgress: true
