CPU_ENERGY_PERF_POLICY_ON_AC=performance
CPU_ENERGY_PERF_POLICY_ON_BAT=balance_power
CPU_ENERGY_PERF_POLICY_ON_SAV=power

PLATFORM_PROFILE_ON_AC=performance
PLATFORM_PROFILE_ON_BAT=balanced
PLATFORM_PROFILE_ON_SAV=low-power

CPU_BOOST_ON_AC=1
CPU_BOOST_ON_BAT=0 # disable turbo boost to use battery more efficiently on continuous workloads
CPU_BOOST_ON_SAV=0

CPU_HWP_DYN_BOOST_ON_AC=1
CPU_HWP_DYN_BOOST_ON_BAT=1 # enable hardware-managed short burst boosting
CPU_HWP_DYN_BOOST_ON_SAV=0
